CREATE TABLE IF NOT EXISTS "Order_detail" (
	"ID"	INTEGER NOT NULL,
	"Order_ID"	INTEGER NOT NULL,
    "Product_ID"	INTEGER NOT NULL,
    "Quantity"	INTEGER,
	"Unit_price"	INTEGER,
	FOREIGN KEY("Order_ID") REFERENCES "Orders"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY("Product_ID") REFERENCES "Products"("ID") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);