CREATE TABLE IF NOT EXISTS orders (
   ID  INTEGER AUTO_INCREMENT primary key,
   User_ID INTEGER NOT NULL,
   Date    DATETIME NOT NULL,
   Status  VARCHAR(255) NOT NULL,
   FOREIGN KEY(User_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
